# Generated by Django 3.2.13 on 2023-04-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20230426_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='Top',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
