# Generated by Django 3.2.13 on 2023-04-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20230426_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Hot',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Top',
        ),
        migrations.AddField(
            model_name='post',
            name='head',
            field=models.BooleanField(default=False, verbose_name='Display at the text panel?'),
        ),
        migrations.AddField(
            model_name='post',
            name='hot',
            field=models.BooleanField(default=False, verbose_name='Is this post important?'),
        ),
        migrations.AddField(
            model_name='post',
            name='top',
            field=models.BooleanField(default=False, verbose_name='Is this a top post?'),
        ),
    ]
