# Generated by Django 3.2.13 on 2023-04-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_auto_20230426_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='original_post',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
