# Generated by Django 3.2.13 on 2023-04-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_auto_20230426_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='head',
        ),
        migrations.RemoveField(
            model_name='post',
            name='top',
        ),
        migrations.AddField(
            model_name='post',
            name='most',
            field=models.BooleanField(default=False, verbose_name='Display at the Most picked Panel?'),
        ),
        migrations.AddField(
            model_name='post',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Display at the Polular Panel?'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, default='#Ucpc', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='hot',
            field=models.BooleanField(default=False, verbose_name='Display at the Hot posts Panel?'),
        ),
    ]
