# Generated by Django 4.0.4 on 2022-04-22 05:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=50)),
                ('logo_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('(\\b\\S*[AĂÂÁẮẤÀẰẦẢẲẨÃẴẪẠẶẬĐEÊÉẾÈỀẺỂẼỄẸỆIÍÌỈĨỊOÔƠÓỐỚÒỒỜỎỔỞÕỖỠỌỘỢUƯÚỨÙỪỦỬŨỮỤỰYÝỲỶỸỴAĂÂÁẮẤÀẰẦẢẲẨÃẴẪẠẶẬĐEÊÉẾÈỀẺỂẼỄẸỆIÍÌỈĨỊOÔƠÓỐỚÒỒỜỎỔỞÕỖỠỌỘỢUƯÚỨÙỪỦỬŨỮỤỰYÝỲỶỸỴAĂÂÁẮẤÀẰẦẢẲẨÃẴẪẠẶẬĐEÊÉẾÈỀẺỂẼỄẸỆIÍÌỈĨỊOÔƠÓỐỚÒỒỜỎỔỞÕỖỠỌỘỢUƯÚỨÙỪỦỬŨỮỤỰYÝỲỶỸỴAĂÂÁẮẤÀẰẦẢẲẨÃẴẪẠẶẬĐEÊÉẾÈỀẺỂẼỄẸỆIÍÌỈĨỊOÔƠÓỐỚÒỒỜỎỔỞÕỖỠỌỘỢUƯÚỨÙỪỦỬŨỮỤỰYÝỲỶỸỴAĂÂÁẮẤÀẰẦẢẲẨÃẴẪẠẶẬĐEÊÉẾÈỀẺỂẼỄẸỆIÍÌỈĨỊOÔƠÓỐỚÒỒỜỎỔỞÕỖỠỌỘỢUƯÚỨÙỪỦỬŨỮỤỰYÝỲỶỸỴAĂÂÁẮẤÀẰẦẢẲẨÃẴẪẠẶẬĐEÊÉẾÈỀẺỂẼỄẸỆIÍÌỈĨỊOÔƠÓỐỚÒỒỜỎỔỞÕỖỠỌỘỢUƯÚỨÙỪỦỬŨỮỤỰYÝỲỶỸỴA-Z]+\\S*\\b){1,}')])),
                ('member1', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^([a-zA-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂẾưăạảấầẩẫậắằẳẵặẹẻẽềềểếỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ]{1,}\\s{0,}){2,7}$')])),
                ('cmnd1', models.CharField(max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^([0-9]{9}|[0-9]{12})$')])),
                ('phone1', models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator('^([0-9]{10}|[0-9]{11})$')])),
                ('member2', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^([a-zA-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂẾưăạảấầẩẫậắằẳẵặẹẻẽềềểếỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ]{1,}\\s{0,}){2,7}$')])),
                ('cmnd2', models.CharField(max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^([0-9]{9}|[0-9]{12})$')])),
                ('phone2', models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator('^([0-9]{10}|[0-9]{11})$')])),
                ('member3', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^([a-zA-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂẾưăạảấầẩẫậắằẳẵặẹẻẽềềểếỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ]{1,}\\s{0,}){2,7}$')])),
                ('cmnd3', models.CharField(max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^([0-9]{9}|[0-9]{12})$')])),
                ('phone3', models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator('^([0-9]{10}|[0-9]{11})$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('paid', models.BooleanField(default=False)),
                ('school1', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='school1', to='register.school')),
                ('school2', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='school2', to='register.school')),
                ('school3', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='school3', to='register.school')),
            ],
        ),
    ]
