# Generated by Django 3.2.13 on 2023-04-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Rank',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
