# Generated by Django 3.2 on 2022-04-26 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_team_school1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='school2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school2', to='register.school'),
        ),
        migrations.AlterField(
            model_name='team',
            name='school3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school3', to='register.school'),
        ),
    ]
