# Generated by Django 3.2 on 2022-04-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20220426_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='school1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='school2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='school3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
