# Generated by Django 3.2.13 on 2023-05-09 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_team_teamname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='MSSV_CMND',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$')]),
        ),
    ]
