# Generated by Django 3.2.13 on 2023-05-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_teammate_mssv_cmnd'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammate',
            name='JobTitle',
            field=models.CharField(default='Pupil/Student', max_length=30),
        ),
    ]
