# Generated by Django 3.2.13 on 2022-05-12 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20220511_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='cmnd1',
            field=models.CharField(max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^([0-9]{9}|[0-9]{12})$')]),
        ),
        migrations.AlterField(
            model_name='team',
            name='cmnd2',
            field=models.CharField(max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^([0-9]{9}|[0-9]{12})$')]),
        ),
        migrations.AlterField(
            model_name='team',
            name='cmnd3',
            field=models.CharField(max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^([0-9]{9}|[0-9]{12})$')]),
        ),
        migrations.AlterField(
            model_name='team',
            name='mssv1',
            field=models.CharField(max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='team',
            name='mssv2',
            field=models.CharField(max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='team',
            name='mssv3',
            field=models.CharField(max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$')]),
        ),
    ]
