# Generated by Django 3.2.13 on 2023-05-11 03:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_team_teamname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='TeamName',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\u00C0-\\u1EF9]+$')]),
        ),
    ]
