# Generated by Django 3.2.13 on 2023-05-11 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_team_teamname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammate',
            name='MSSV_CMND',
        ),
        migrations.AddField(
            model_name='teammate',
            name='CMND_CCCD',
            field=models.CharField(default='00000000', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^([0-9]{9}|[0-9]{12})$')]),
        ),
        migrations.AddField(
            model_name='teammate',
            name='MSSV',
            field=models.CharField(default='22520000', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='JobTitle',
            field=models.CharField(default='Pupil/Student', max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$')]),
        ),
    ]
