# Generated by Django 3.2.13 on 2023-05-11 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20230511_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='CMND_CCCD',
            field=models.CharField(default='000000000', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^([0-9]{9}|[0-9]{12})$')]),
        ),
    ]
