# Generated by Django 3.2.13 on 2023-04-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo_path',
            field=models.CharField(default='*', max_length=100),
            preserve_default=False,
        ),
    ]
