# Generated by Django 3.2.13 on 2023-05-11 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_alter_teammate_jobtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='MSSV',
            field=models.CharField(default='22520000', max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$')]),
        ),
    ]
