# Generated by Django 3.2.13 on 2023-04-19 06:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_school_logo_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Date', models.DateField(max_length=20)),
                ('Title', models.CharField(max_length=50, unique=True)),
                ('Author', models.CharField(default='Đoàn-Hội Khoa Học Máy Tính UIT', max_length=30)),
                ('Thumbnail', models.URLField(default='https://www.facebook.com/DoanHoiKHMT')),
                ('Post', models.URLField(default='https://www.facebook.com/DoanHoiKHMT')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Fullname', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂẾưăạảấầẩẫậắằẳẵặẹẻẽềềểếỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳýỵỷỹ\\s\\W|_]+$')])),
                ('MSSV_CMND', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^([0-9]{8}|[0-9]{9}|[0-9]{12})$')])),
                ('Phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('(84|0[3|5|7|8|9])+([0-9]{8})\\b')])),
                ('School', models.CharField(choices=[], max_length=10)),
                ('Admin', models.BooleanField(default=False)),
                ('Leader', models.BooleanField(default=False)),
                ('Occupation', models.CharField(choices=[('ST', 'Student'), ('PP', 'Pupil'), ('TC', 'Teacher')], default='ST', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=30)),
                ('Year', models.IntegerField(validators=[django.core.validators.RegexValidator('^\\d{4}$')])),
                ('Deadline', models.DateTimeField()),
                ('Law', models.JSONField()),
                ('Award', models.JSONField()),
                ('Timeline', models.JSONField()),
                ('Organization', models.JSONField()),
                ('Sponsor', models.JSONField()),
                ('Social', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team',
            new_name='TeamName',
        ),
        migrations.RemoveField(
            model_name='team',
            name='cmnd1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='cmnd2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='cmnd3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='mssv1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='mssv2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='mssv3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='team',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='phone3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='school1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='school2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='school3',
        ),
        migrations.AddField(
            model_name='team',
            name='FeePayment',
            field=models.CharField(choices=[('PEND', 'Pending'), ('CMPL', 'Completed'), ('FAIL', 'Failed')], default='PEND', max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='team',
            name='Rank',
            field=models.IntegerField(default=-1, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.team'),
        ),
    ]
