# Generated by Django 3.2.13 on 2023-05-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_alter_teammate_mssv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='School',
            field=models.CharField(max_length=10),
        ),
    ]
