# Generated by Django 3.2.13 on 2023-04-19 09:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20230419_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Fullname', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂẾưăạảấầẩẫậắằẳẵặẹẻẽềềểếỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳýỵỷỹ\\s\\W|_]+$')])),
                ('MSSV_CMND', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^([0-9]{8}|[0-9]{9}|[0-9]{12})$')])),
                ('Phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('(84|0[3|5|7|8|9])+([0-9]{8})\\b')])),
                ('School', models.CharField(choices=[], max_length=10)),
                ('Leader', models.BooleanField(default=False)),
                ('Occupation', models.CharField(choices=[('ST', 'Student'), ('PP', 'Pupil'), ('TC', 'Teacher')], default='ST', max_length=10)),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.team')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
