# Generated by Django 3.2.13 on 2023-04-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20230419_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='School',
            field=models.CharField(choices=[('UIT', 'Đại học Công nghệ Thông tin - Đại học quốc gia thành phố Hồ Chí Minh')], max_length=10),
        ),
    ]
