# Generated by Django 3.2.13 on 2023-05-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_alter_teammate_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='Award',
        ),
        migrations.RemoveField(
            model_name='website',
            name='Law',
        ),
        migrations.RemoveField(
            model_name='website',
            name='Organization',
        ),
        migrations.RemoveField(
            model_name='website',
            name='Social',
        ),
        migrations.RemoveField(
            model_name='website',
            name='Sponsor',
        ),
        migrations.RemoveField(
            model_name='website',
            name='Timeline',
        ),
        migrations.RemoveField(
            model_name='website',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='website',
            name='Year',
        ),
        migrations.AddField(
            model_name='website',
            name='PublicDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='Deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
