# Generated by Django 3.2.13 on 2023-05-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_auto_20230513_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='Title',
            field=models.CharField(default='UCPC', max_length=30),
        ),
    ]
